server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/mydb01
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: cn.itcast.user.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug