let provinces = [
    {
        pid:1,
        pname:"上海",
        cities:[
            {
                cid:11,
                cname:"浦东新区"
            },
            {
                cid:12,
                cname:"静安区"
            },
            {
                cid:13,
                cname:"嘉定区"
            }
        ]
    },
    {
        pid:2,
        pname:"北京",
        cities:[
            {
                cid:21,
                cname:"顺义区"
            },
            {
                cid:22,
                cname:"朝阳区"
            },
            {
                cid:23,
                cname:"丰台区"
            }
        ]
    },
    {
        pid:3,
        pname:"广州",
        cities:[
            {
                cid:31,
                cname:"白云区"
            },
            {
                cid:32,
                cname:"花都区"
            },
            {
                cid:33,
                cname:"南沙区"
            }

        ]
    },
]