server:
  port: 9004
spring:
  application:
    name: leadnews-wemedia
  kafka:
    bootstrap-servers: 192.168.200.130:9092
    producer:
      retries: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:8848
    alibaba:
      seata:
        tx-service-group: heima_leadnews_tx_group
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.200.130:3306/leadnews_wemedia?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 10MB
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.heima.model.media.pojos
logging:
  level:
    com.heima: debug  # 日志打印级别
hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 5000 # 设置线程隔离时间
ribbon:
  ReadTimeout: 5000   # 读取超时时长
  ConnectTimeout: 2000   # 建立链接的超时时长
#OSS配置
file:
  oss:
    bucket-name: hmtt128   # 桶 存储空间名称
    access-key-id: LTAI5tQpuFC6ZMTkUnzCoYHY   # 密钥
    access-key-secret: rOx9bai1cmEPdrIOpF9aa8OEhTROlz
    endpoint: oss-cn-shanghai.aliyuncs.com  #地域
    web-site: https://hmtt128.oss-cn-shanghai.aliyuncs.com/  # 访问前缀
    proxy-username: aliyun-sdk-java
    socket-timeout: 10000
    idle-connection-time: 10000
    connection-request-timeout: 4000
    max-connections: 2048
    max-error-retry: 5
    white-list: 127.0.0.1
    connection-timeout: 10000
    prefix: material   # 文件夹前缀   OSS：   material 文件夹
  minio:
    accessKey: minio
    secretKey: minio123
    bucket: hmtt128
    endpoint: http://192.168.200.130:9090/
    readPath: http://192.168.200.130:9090/
feign:
  hystrix:
    enabled: true # 开启熔断
